"""XS script bundling.

AoE2:DE does not ship loose ``.xs`` files to other players in a lobby, so the only
reliable way to distribute script logic is to embed it in the scenario itself. The
parser does that via a disabled "XS SCRIPT" trigger whose script-call effect carries
the whole file; ``xs_manager.add_script(xs_string=...)`` is that path.

That means the repo can keep XS in normal, lintable, diffable files and concatenate
them at build time.
"""

from __future__ import annotations

import re
from collections.abc import Mapping
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from aoe2modes.context import BuildContext

_PLACEHOLDER = re.compile(r"\$\{(\w+)\}")


class XsError(RuntimeError):
    pass


def substitute(source: str, values: Mapping[str, object], *, origin: str = "<xs>") -> str:
    """Replace every ``${NAME}`` placeholder, erroring on any that has no value.

    Placeholders let a mode inject build-time constants (wave pacing, player count,
    spawn coordinates) into XS instead of duplicating them on both sides. Leaving one
    unsubstituted would ship broken XS, so it is always an error rather than a warning.
    """
    missing: list[str] = []

    def replace(match: re.Match[str]) -> str:
        key = match.group(1)
        if key not in values:
            missing.append(key)
            return match.group(0)
        return str(values[key])

    result = _PLACEHOLDER.sub(replace, source)
    if missing:
        raise XsError(
            f"{origin}: no build-time value for {sorted(set(missing))}. "
            f"Set it with ctx.set_xs_vars(...) in build.py."
        )
    return result


def read_xs(path: Path, values: Mapping[str, object] | None = None) -> str:
    """Read an XS file and substitute its placeholders."""
    if not path.is_file():
        raise XsError(f"XS file not found: {path}")
    return substitute(path.read_text(encoding="utf-8"), values or {}, origin=str(path))


def resolve_sources(ctx: BuildContext) -> list[tuple[str, Path]]:
    """The ordered list of XS files for a mode: shared includes, then its own scripts."""
    sources: list[tuple[str, Path]] = []
    for relative in ctx.spec.xs.include:
        sources.append((f"xs/{relative}", ctx.repo.shared_xs / relative))
    for relative in ctx.spec.xs.scripts:
        sources.append((f"{ctx.spec.id}/{relative}", ctx.mode_dir / relative))

    for label, path in sources:
        if not path.is_file():
            raise XsError(f"{ctx.spec.id}: XS source listed in mode.toml is missing: {label} -> {path}")
    return sources


def bundle_xs(ctx: BuildContext) -> str:
    """Concatenate every XS source for a mode into the single file DE will run.

    Returns an empty string when the mode has no XS at all, so the caller can skip
    creating the XS trigger entirely.
    """
    sources = resolve_sources(ctx)
    if not sources and not ctx.xs_chunks:
        return ""

    parts = [
        f"// Generated by aoe2modes for '{ctx.spec.id}' v{ctx.spec.version}.",
        "// Do not edit in-game: edit the .xs files in this repo and rebuild.",
        "",
    ]
    for label, path in sources:
        parts += [f"// ---- {label} ----", read_xs(path, ctx.xs_vars).rstrip(), ""]
    for label, source in ctx.xs_chunks:
        parts += [
            f"// ---- {label} (inline) ----",
            substitute(source, ctx.xs_vars, origin=label).rstrip(),
            "",
        ]

    ctx.log(f"bundled {len(sources)} XS file(s) + {len(ctx.xs_chunks)} inline chunk(s)")
    return "\n".join(parts)
