// ------------------------- XS string -------------------------
// Generated by aoe2modes for 'cba_hero' v0.1.0.
// Do not edit in-game: edit the .xs files in this repo and rebuild.

// ---- xs/lib/util.xs ----
// Shared helpers used by every mode in this repo.
// Included via `xs.include = ["lib/util.xs"]` in a mode.toml.

// Trigger-variable ids that XS and the trigger layer agree on.
// Keep these in sync with aoe2modes.lib.variables in the Python side.
const int VAR_WAVE          = 0;
const int VAR_WAVE_SIZE     = 1;
const int VAR_MATCH_SECONDS = 2;

void logLine(string message = "") {
    xsChatData("[cba] " + message);
}

int clampInt(int value = 0, int low = 0, int high = 0) {
    if (value < low) {
        return (low);
    }
    if (value > high) {
        return (high);
    }
    return (value);
}

int maxInt(int a = 0, int b = 0) {
    if (a > b) {
        return (a);
    }
    return (b);
}

int minInt(int a = 0, int b = 0) {
    if (a < b) {
        return (a);
    }
    return (b);
}

// Whole seconds since the match started. xsGetTime() reports milliseconds.
int matchSeconds() {
    return (xsGetTime() / 1000);
}

// Publish a value so trigger conditions ("Variable Value") can read it.
void publish(int variableId = 0, int value = 0) {
    xsSetTriggerVariable(variableId, value);
}

// ---- xs/lib/random.xs ----
// Randomness helpers.
//
// Every player's XS instance runs the same code on the same seed, so these stay in
// sync across a multiplayer lobby as long as they are only called from rules that
// every player runs. Never branch on xsGetLocalPlayerId() before calling them.

// Inclusive on both ends. xsGetRandomNumberMax(n) yields 0..n-1.
int randRange(int low = 0, int high = 0) {
    if (high <= low) {
        return (low);
    }
    return (low + xsGetRandomNumberMax(high - low + 1));
}

// Returns true with `percent` probability.
bool chance(int percent = 50) {
    return (randRange(1, 100) <= percent);
}

// Pick a random entry from an int array created with xsArrayCreateInt.
int randomFrom(int arrayId = -1) {
    int size = xsArrayGetSize(arrayId);
    if (size <= 0) {
        return (-1);
    }
    return (xsArrayGetInt(arrayId, randRange(0, size - 1)));
}

// ---- cba_hero/xs/main.xs ----
// CBA Hero — match clock and wave pacing.
//
// Division of labour with the trigger layer:
//   * XS owns the clock. It counts waves, scales wave size, and publishes both into
//     trigger variables so trigger conditions can gate on them.
//   * Triggers own the map. Spawning and attack-move orders need concrete tile
//     coordinates, which the Python build already knows.
//
// Constants marked ${...} are substituted at build time by aoe2modes.lib.xs.read_xs,
// so mode.toml stays the single source of truth for pacing.

const int WAVE_INTERVAL_SECONDS = 20;
const int WAVE_SIZE_BASE        = 4;
const int WAVE_SIZE_STEP        = 1;
const int WAVE_SIZE_CAP         = 16;

int gWave = 0;

// Wave size grows linearly and then plateaus, so late-game lag stays bounded.
int waveSizeFor(int wave = 0) {
    return (minInt(WAVE_SIZE_BASE + (wave * WAVE_SIZE_STEP), WAVE_SIZE_CAP));
}

void main() {
    gWave = 0;
    publish(VAR_WAVE, 0);
    publish(VAR_WAVE_SIZE, waveSizeFor(0));
    publish(VAR_MATCH_SECONDS, 0);
    logLine("Match start. First wave in " + WAVE_INTERVAL_SECONDS + "s.");
}

rule matchClock
    active
    minInterval 1
{
    publish(VAR_MATCH_SECONDS, matchSeconds());
}

rule waveTick
    active
    minInterval 1
{
    xsSetRuleMinIntervalSelf(WAVE_INTERVAL_SECONDS);

    gWave = gWave + 1;
    publish(VAR_WAVE, gWave);
    publish(VAR_WAVE_SIZE, waveSizeFor(gWave));

    if (gWave % 5 == 0) {
        logLine("Wave " + gWave + " — reinforcements growing.");
    }
}

